language: r
r:
  - release
cache: packages
latex: false
sudo: false

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e "library(covr); codecov(line_exclusions = list('R/brms_SummaryTable.R'=67:70,
                               'R/addins.R'),
        function_exclusions = list('update_github_pkgs')))"
